### ISSUE TITLE
Invalid Function Arguments (main.tf)

### ISSUE THREAD

**Issue by 1benyork** [piartz/aws-dr-terraform#1]
**Wondering if I can get some help here?**

│ Error: Invalid function argument
│ 
│   on main.tf line 40, in resource "aws_launch_template" "webserver_lt":
│   40:   user_data     = "${base64encode(templatefile("user_data.tftpl",{}))}"
│     ├────────────────
│     │ while calling templatefile(path, vars)
│ 
│ Invalid value for "path" parameter: no file exists at "user_data.tftpl"; this function
│ works only with files that are distributed as part of the configuration source code, so
│ if this file will be created by a resource in this configuration you must instead obtain
│ this result from an attribute of that resource.

**Comment by piartz** [comment]
Hi @1benyork :) 

There is a typo in the filename for `user_data.tftpl`. I will change the extension name on the repository. You can rename `user_data.tfpl` to `user_data.tftpl` to make it work. Nice catch! Let me know if it works and I will close the issue.

**Comment by 1benyork** [comment]
Yes that solved the issue! Thank you so much!
